### PR TITLE
homepage created

### PR DESCRIPTION
**Pull request by ORKO06**
added navbar
added landing page
added animation
added responsivenss

### CODE REVIEW

**Comment by m-code12** [comment]
@ORKO06 Please attach screenshots.

**Comment by ORKO06** [comment]
Screenshot 2021-02-20 122143

**Comment by ORKO06** [comment]
Screenshot 2021-03-05 235341
Screenshot 2021-03-05 235404
Screenshot 2021-03-05 235423
Screenshot 2021-03-05 235440

**Comment by m-code12** [comment]
Good job 🚀 @ORKO06

**Pull request merged**
